// © 2026 arun•°Cumar. All Rights Reserved.

export default async function tagAll(sock, msg, args) {
    const chatId = msg.key.remoteJid;

    if (!chatId.endsWith('@g.us')) {
        return await sock.sendMessage(chatId, { text: '❌ This command can only be used in groups.' });
    }

    try {
        const groupMetadata = await sock.groupMetadata(chatId);
        const participants = groupMetadata.participants;

        if (!participants || participants.length === 0) {
            return await sock.sendMessage(chatId, { text: 'No participants found.' });
        }

        let text = `📢 *TAG ALL MEMBERS*\n\n`;
        text += `✨ *Group:* ${groupMetadata.subject}\n`;
        text += `👥 *Total:* ${participants.length}\n\n`;
        text += `───────────────────\n`;

        for (let mem of participants) {
            text += `🔹 @${mem.id.split('@')[0]}\n`;
        }

        text += `───────────────────\n\n`;
        text += `*Generated by Nexa-MD* 🚀`;

        await sock.sendMessage(chatId, {
            text: text,
            mentions: participants.map(p => p.id)
        }, { quoted: msg });

    } catch (error) {
        console.error("TagAll Modern Error:", error);
        await sock.sendMessage(chatId, {
            text: '❌ Failed to tag all members. Make sure I am an admin.'
        });
    }
}
